import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "~/components/Button";


const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-full flex justify-center items-center md:h-[calc(100vh-100px)] ">
    <div className="max-w-[950px] flex flex-col md:flex-row-reverse  justify-center items-center w-full px-[16px] gap-4 md:justify-between">
      <div className="relative h-[313px] w-[300px]">
      <Image 
      alt="Home Hero Image"
      fill 
      src="/hero.png"
      />
      </div>
      <div className="flex justify-start w-full items-start  flex-col space-y-3 lg:max-w-[500px] md:max-w-[300px]">
        <h2 className="font-bold text-[32px] lg:text-[42px] leading-[36px] md:leading-[50px] text-bg-dark dark:text-bg-light">
        Generate icons with a click of a button
        </h2>
        <p className="text-text-sec-light dark:text-text-sec-dark lg:text-lg">
        Use AI to generate icons in one click instead of paying a designer and 
        waiting for them.
        </p>
        <Button>
          Generate Icon
        </Button>
      </div>
    </div>
    <div className="absolute bottom-0 right-0 h-full w-full -z-10 ">
    <Image src="/meshh.png" alt="Hero Image" fill/>
    </div>
    </section>
    </>
  );
};

export default HomePage;