import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "~/components/Button";
import GenerateModal from "~/components/GenerateModal";
import  PrimaryLinkButton  from "~/components/PrimaryLinkButton";
import useGenerateModal from "~/hooks/useGenerateModal";

const HeroBanner = () => {
  const generateModal = useGenerateModal();
  return (
    <>
    {
      generateModal.isOpen && (
        <GenerateModal />
      )
    }
    <section className="w-full flex justify-center items-center ">
    <div className="grid grid-cols-12 w-full max-w-[1200px] justify-items-center justify-center items-center pt-20">
      <Button
      onClick={generateModal.onOpen}
      variant="cta">
        open 
      </Button>
      <div className="flex flex-col gap-4 col-start-2 col-end-8">
        <h1 className="text-6xl">Generate icons with a click of a button</h1>
        <p className="text-2xl">
          Use AI to generate icons in seconds instead of paying a designer and
          waiting for them to create them for you.
        </p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generated your Icons
        </PrimaryLinkButton>
      </div>
      <Image
        src="/banner.png"
        alt="an image of a bunch of nice looking icons"
        width="400"
        height="300"
        className="col-start-8 col-end-12 rounded"
      />
      </div>
    </section>
    </>
  );
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;